#!/usr/bin/env python3
"""从一张照片生成 avatar_assets.c（closed + open 两帧 RGB565 135x240）。

只动嘴部小区域，其它像素 closed/open 完全一致 → 帧切换时头不会跳。

用法：
    python3 gen_avatar_assets.py <input.jpg> [--out main/display/avatar_assets.c] \
        [--mouth-x 68 --mouth-y 118 --mouth-w 18 --mouth-h 6] \
        [--crop-x 133 --crop-y 0 --crop-w 253 --crop-h 450] \
        [--preview]

--preview 同时把 closed/open 两帧存为 PNG，方便先看效果再编进固件。
"""

from __future__ import annotations
import argparse
from pathlib import Path
from PIL import Image, ImageDraw

W, H = 135, 240


def rgb565_bytes(im: Image.Image) -> bytes:
    """RGB888 → RGB565 little-endian。LVGL 默认就是 LE。"""
    assert im.mode == "RGB" and im.size == (W, H)
    out = bytearray(W * H * 2)
    px = im.load()
    i = 0
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            out[i] = v & 0xFF
            out[i + 1] = (v >> 8) & 0xFF
            i += 2
    return bytes(out)


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] __attribute__((aligned(4))) = {{"]
    for chunk_start in range(0, len(data), 16):
        chunk = data[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(name: str, data_name: str) -> str:
    return (
        f"const lv_img_dsc_t {name} = {{\n"
        f"    .header = {{ .cf = LV_COLOR_FORMAT_RGB565, .w = {W}, .h = {H} }},\n"
        f"    .data_size = sizeof({data_name}),\n"
        f"    .data = {data_name},\n"
        f"}};"
    )


def make_closed(src: Image.Image, crop: tuple[int, int, int, int]) -> Image.Image:
    cx, cy, cw, ch = crop
    cropped = src.crop((cx, cy, cx + cw, cy + ch))
    return cropped.resize((W, H), Image.LANCZOS).convert("RGB")


def make_open(closed: Image.Image, mouth: tuple[int, int, int, int]) -> Image.Image:
    """在 closed 上叠一个深色椭圆模拟张嘴。其它像素一字不动 → 不跳帧。"""
    mx, my, mw, mh = mouth
    out = closed.copy()
    draw = ImageDraw.Draw(out)
    # 外圈深棕（嘴唇内沿阴影），内圈接近黑色（口腔）
    draw.ellipse((mx - mw // 2, my - mh // 2, mx + mw // 2, my + mh // 2),
                 fill=(40, 18, 18))
    inner_w, inner_h = max(2, mw - 4), max(1, mh - 2)
    draw.ellipse((mx - inner_w // 2, my - inner_h // 2,
                  mx + inner_w // 2, my + inner_h // 2),
                 fill=(15, 5, 5))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("--out", default="main/display/avatar_assets.c")
    ap.add_argument("--crop-x", type=int, default=133)
    ap.add_argument("--crop-y", type=int, default=0)
    ap.add_argument("--crop-w", type=int, default=253)
    ap.add_argument("--crop-h", type=int, default=450)
    ap.add_argument("--mouth-x", type=int, default=68)
    ap.add_argument("--mouth-y", type=int, default=118)
    ap.add_argument("--mouth-w", type=int, default=18)
    ap.add_argument("--mouth-h", type=int, default=6)
    ap.add_argument("--preview", action="store_true",
                    help="同时输出 PNG 预览到 build/avatar_preview/")
    args = ap.parse_args()

    src = Image.open(args.input).convert("RGB")
    crop = (args.crop_x, args.crop_y, args.crop_w, args.crop_h)
    mouth = (args.mouth_x, args.mouth_y, args.mouth_w, args.mouth_h)

    closed = make_closed(src, crop)
    opened = make_open(closed, mouth)

    if args.preview:
        prev = Path("build/avatar_preview")
        prev.mkdir(parents=True, exist_ok=True)
        closed.save(prev / "avatar_close.png")
        opened.save(prev / "avatar_open.png")
        print(f"preview -> {prev}/avatar_close.png, avatar_open.png")

    closed_bytes = rgb565_bytes(closed)
    opened_bytes = rgb565_bytes(opened)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write("/* Auto-generated by scripts/gen_avatar_assets.py — do not edit. */\n")
        f.write("#include <stdint.h>\n")
        f.write('#include "lvgl.h"\n\n')
        f.write(emit_array("avatar_close_data", closed_bytes) + "\n\n")
        f.write(emit_dsc("avatar_close", "avatar_close_data") + "\n\n")
        f.write(emit_array("avatar_open_data", opened_bytes) + "\n\n")
        f.write(emit_dsc("avatar_open", "avatar_open_data") + "\n")
    print(f"wrote {out_path} (closed={len(closed_bytes)}B open={len(opened_bytes)}B)")


if __name__ == "__main__":
    main()
